public class c_event_constants {
    public static final String msg_cannot_blank = 'All input with * marked cannot be blank';
    public static final String msg_failed_save_data = 'Failed saving your data.';
    public static final String msg_invalid_booking_code = 'Booking Code invalid!';
	public static final String msg_email_cannot_blank = 'email must be filled!';
    public static final String msg_email_invalid = 'email must valid!';
    public static final String msg_must_select_min_a_event_session = 'You must select min a Event Session!';
    public static final String msg_failed_save_email = 'Registration failed. Failed to save your email.';
    public static final String contact_last_name = 'bb_lastname';
    
    public static final String msg_unable_change_limit = 'Operation failed, you can\'t change limit at this moment';
}